blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/svallory/mitosis-plugins/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Vulnerability
    url: https://github.com/svallory/mitosis-plugins/security/policy
    about: Please report security vulnerabilities privately
